fix: Exporting AuthoringUtils required for remote app
adobe/aem-spa-page-model-manager pull request #47
Opened 2021-02-04 11:17 UTC by SushantBhasin

## Description

Exposing Authoring utils to be used in related PR https://github.com/adobe/aem-react-editable-components/pull/51

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-02-05 08:02 UTC, blackbyte-pl approved these changes

2021-02-09 12:54 UTC, grubyak requested changes
Please do not duplicate code in this way:
https://github.com/adobe/aem-spa-page-model-manager/blob/e7adcf008d5a99738bc98afd12ec56e41d584270/src/AuthoringUtils.ts#L133-L153

2021-02-09 13:38 UTC, CezCz reviewed
Please add tests

2021-02-10 10:15 UTC, CezCz approved these changes

2021-02-10 10:20 UTC, grubyak approved these changes

2021-02-10 11:23 UTC, merged